### PR TITLE
Fixed building error on Mac OS

### LINKED ISSUE #308: build on mac has error
**Describe the bug**
when you want to build ext on mac os, it has error:

`

> ➜  ext make
> /bin/ksh /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/libtool --mode=compile cc  -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/backend_comm.c -o backend_comm.lo
> mkdir .libs
>  cc -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/backend_comm.c  -fno-common -DPIC -o .libs/backend_comm.o
> /bin/ksh /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/libtool --mode=compile cc  -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c -o ConfigManager.lo
>  cc -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c  -fno-common -DPIC -o .libs/ConfigManager.o
> In file included from /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c:25:
> In file included from ./elastic_apm_alloc.h:20:
> ./platform.h:15:13: fatal error: 'features.h' file not found
> \#   include <features.h>
>             ^~~~~~~~~~~~
> 1 error generated.
> make: *** [ConfigManager.lo] Error 1
> 

**To Reproduce**
1. get mac os big sur
2. then install php 7.4
3. then try to make package

**Expected behavior**
it should build :)

### PR DESCRIPTION
**Pull request by SergeyKleyman**
Closes #308

### CODE REVIEW

**Comment by dangoscomb** [comment]
This does not build on OSX still.

```
In file included from /tmp/apm-agent-php/src/ext/ConfigManager.c:33:
In file included from ./elastic_apm_alloc.h:28:
./platform.h:24:17: fatal error: 'features.h' file not found
#       include <features.h>
                ^~~~~~~~~~~~
```

GCC is installed, hence the issue I would assume.

try ```ifndef __APPLE__``` perhaps? The issue is this is not the only build error. The sys/sysinfo.h stuff also fails after this one is fixed as that also doesn't exist on osx.

**Comment by SergeyKleyman** [comment]
@dangoscomb Hi. Did you have a chance to test the latest update (i.e., with `! defined( __APPLE__ )`) to this PR?

**Comment by dangoscomb** [comment]
Hi

I have not, however I did it this way:

https://github.com/dangoscomb/apm-agent-php/tree/osx-build

As mentioned in the issue it builds but I have not yet tested it works properly. Have you considered a build and test on a GitHub action running on OSX?

**Comment by webpatser** [comment]
Latest version still has an error compiling. Would be nice to have this compiling an a Mac.

```
./TextOutputStream.h:47:33: error: redefinition of typedef 'TextOutputStream' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef struct TextOutputStream TextOutputStream;
                                ^
./elastic_apm_assert.h:210:33: note: previous definition is here
typedef struct TextOutputStream TextOutputStream;
                                ^
2 errors generated.
make: *** [AST_instrumentation.lo] Error 1
```

using home-brew installed php and build tools:

```
gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
```

**Comment by v1v** [comment]
run docs-build

**Comment by intuibase** [comment]
We will close it for now as it has low priority. We can always can back to MacOS build in future.

**Pull request closed without merging**
