### PR TITLE
New service configuration parameters for apm

### PR DESCRIPTION
**Pull request by miguelsimoes**

### CODE REVIEW

**Comment by SergeyKleyman** [comment]
Hi @miguelsimoes,

Thank you very much for contributing to PHP Agent - community contributions are always welcome.

I strongly recommend to read [Contributing to the Elastic APM PHP agent document](https://github.com/elastic/apm-agent-php/blob/master/CONTRIBUTING.md) first. For example, you would see that it's necessary to sign the Contributor License Agreement before submitting your changes.

Regarding this PR:
1. Could you please clarify what is the goal of this PR?
2. I see that you are trying to add three new configuration options: `environment`, `service_node_name` and `service_version` but you are trying to add the options to C part of the agent but it would make much more sense to add handling of those configuration options to PHP part of the agent because PHP part is the one that will use them (in this case in order to construct metadata part of the events sent to APM Server). Funnily enough `environment` and `service_version` were already added and part of master (PRs #126 and #105).
3. `service_node_name` configuration option - could you please clarify what is the use case you would like to cover with this option? AFAIK this option is used only for metrics and PHP Agent doesn't send any metrics at the moment so I'm not sure what use would it have. But if you would like to add it nonetheless - I opened an issue for it (#143) and I recommend to look at changes in #126 (the ones that are related to `environment` configuration option). Also you will need to extend [`ServiceDataInterface`](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/ServiceDataInterface.php) to include [`node` part](https://github.com/elastic/apm-agent-php/blob/master/tests/APM_Server_intake_API_schema/latest_used/docs/spec/service.json#L85) of APM Server Intake API spec.
4. Regarding C part of the agent - we prefer to keep its responsibilities to the minimum because C code is harder to get right than PHP code so community will have less opportunity to contribute. So if something can be done via PHP part of the agent that is the approach that should be preferred.

**Comment by miguelsimoes** [comment]
Hello Sergei,

1. The goal of this PR is to provide support on C part for the service_name and environment (already present on PHP) and to add a new option that exists on the Java agent and very useful regarding the docker node where the application is running.
2. The service_version and environment were already present on the PHP but not on the module (so they wouldn't get populated on when the transaction was initialized). The service_node_name is something already provided on the Java agent and very useful when running on docker instances.
3. Please see https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-service-node-name
4. I did try to add new properties to the PHP part, however the ServiceData is immutable and not able to receive new parameters after it has been initialised (if you could tell how I could achieve that on PHP, I would really prefer to do it on PHP).

**Comment by SergeyKleyman** [comment]
> service_version and environment were already present on the PHP but not on the module (so they wouldn't get populated on when the transaction was initialized)

C part of the agent automatically bootstraps PHP part so whatever PHP part does is done automatically. You can easily see [in the code](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/MetadataDiscoverer.php#L56) that all these configuration options (`environment`, `service_node_name` and `service_version`) do is to make agent to copy their values to the corresponding `metadata`'s `service.*` parts (you can see the corresponding APM Server Intake API spec [here](https://github.com/elastic/apm-server/blob/master/docs/spec/service.json#L61).

> ServiceData is immutable and not able to receive new parameters after it has been initialised

It's not exactly the case since all the fields in `ServiceData` are just `protected` and not `private` so [you can see that `ServiceData` is changed while it's being built by `MetadataDiscoverer`](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/MetadataDiscoverer.php#L56). I agree that it's a quite contrived and unnecessarily complicated. I have a PR (#120) in progress to simplify this part by removing `ServiceDataInterface` and making `ServiceData` simple mutable DTO.

For now I would recommend to just follow `environment` configuration option example since the way `environment` and `service_node_name` configuration options are treated by the agent is exactly the same - agent just copies configuration option value to the corresponding `metadata`'s `service.*` part. The only additional work required for `service_node_name` is to add the corresponding part to `ServiceData`. I would recommend adding simple mutable DTO class (let's say `ServiceNodeData`). 

Since this part of the code is in flux somewhat I thought I might show you the necessary changes - I've opened #144. Could please try it and let me know if it works for you?

**Comment by SergeyKleyman** [comment]
> to provide support on C part for the service_version and environment (already present on PHP)

> service_version and environment were already present on the PHP but not on the module (so they wouldn't get populated on when the transaction was initialized)

Could you please clarify what is not working as expected? Why do you think that `they wouldn't get populated`? [In the code](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/Tracer.php#L83) you can that `metadata` is built when `Tracer` is constructed and [then this `Tracer` is used to create `transaction`](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php#L35) representing the whole request (request from C extension point of view).

**Comment by miguelsimoes** [comment]
Using the environment as an example, the following is missing (and the remaining C changes required):
https://github.com/elastic/apm-agent-php/pull/142/commits/066022828f8d0881957365372d063b779e6459b6#diff-2044f371292709c7a26f3c27de28a421R570

The same is applied to service_version (also missing)

**Comment by SergeyKleyman** [comment]
Could you please describe your scenario in details when setting `service_version` configuration option doesn't work as expected?
For example:
1. Do you setup the agent according to [these instructions](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc)?
2. How do you set `service_version` configuration option - using `php.ini` or environment variables?
3. Did you make sure you select time range in Kibana after the agent was updated and did you refresh the browser? [According to other users experience](https://github.com/elastic/apm-agent-php/issues/125#issuecomment-676224265) the reason setting configuration option doesn't have the desired effect is because the browser might still show data sent by the old version of the agent.

**Comment by SergeyKleyman** [comment]
I posted the previous comment before seeing the additions you have made to your last comment :)
So I assume the answer to 

> How do you set service_version configuration option - using php.ini or environment variables?

is `php.ini`, right?

**Comment by SergeyKleyman** [comment]
> var_dump(ini_get_all('elastic_apm', false));

You can see [in the code](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/Config/IniRawSnapshotSource.php#L39) that `IniRawSnapshotSource` calls `ini_get_all(/* extension: */ null, /* details */ false)` - it passes `null` as extension name in order to avoid requirement to register all the option names in extension.

**Comment by miguelsimoes** [comment]
The behaviour using `null` or the extension is the same (was to limit the output of the dump). In this case, I am using the elastic_apm.ini file to define the version and the environment.

Question: if the C part does not have the handler to retrieve the environment parameter from the ini file, how does it reach the IniRawSnapshotSource in the `ini_get_all` call?

**Comment by SergeyKleyman** [comment]
> Question: if the C part does not have the handler to retrieve the environment parameter from the ini file, how does it reach the IniRawSnapshotSource in the `ini_get_all` call?

I'm not 100% I understand your question. `IniRawSnapshotSource` is not called because of `ini_get_all` call - as you can see in the code it's the other way around - `IniRawSnapshotSource` calls `ini_get_all`. As part of bootstrap sequence for each request [C part of the agent calls](https://github.com/elastic/apm-agent-php/blob/master/src/ext/lifecycle.c#L212) `src/bootstrap_php_part.php` (that is the reason full path to `bootstrap_php_part.php` needs to be provided as value of `elastic_apm.bootstrap_php_part_file` option when [setting up the agent](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc)). From `bootstrap_php_part.php` bootstrap sequence reaches Tracer's getConfig() method that [uses](https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/Tracer.php#L94) `IniRawSnapshotSource` and `EnvVarsRawSnapshotSource` to read and parse configuration.

I would love to help you out but I still not sure what is not working for you. I would recommend to put aside your change for a moment and try the current master. If it doesn't work we will try to find out why and fix it.

**Comment by miguelsimoes** [comment]
1. Extension loads ini file with provided configuration
2. IniRawSnapshotSource calls `ini_get_all`method
3. On the values returned by ini_get_all `service_version` and `environment` are missing

Looking at `ConfigManager.h`you can see that the options `environment` and `service_version` are missing, so they are not loaded from the ini file.

**Comment by miguelsimoes** [comment]
Tried your solution and didn't work. The ini file I am using is:
`; Licensed to Elasticsearch B.V. under one or more agreements.
; Elasticsearch B.V. licenses this file to you under the Apache 2.0 License.
; See the LICENSE file in the project root for more information

[elastic_apm]

;
; Elastic PHP APM Agent
;
; See: https://github.com/elastic/apm-agent-php
;
extension = elastic_apm.so

; Boolean flag to enable/disable all of the agent's functionality.
; Possible values:
;   false = Disabled
;   true = Enabled
; Default value: true
elastic_apm.enabled = true

; Location of the
elastic_apm.log_file = "/var/log/directus/apm.log"

;;;;;;;;;;;;;;;;;;;;;;;;;
; Monitored service     ;
;;;;;;;;;;;;;;;;;;;;;;;;;

elastic_apm.environment = "production"

; The required service's name to identify it later in the APM UI
; Please change to a to your use case appropiate name.
elastic_apm.service_name = "application-name"

; Set the service's version to compare historical private between deployments
; Default value: none
elastic_apm.service_version = "1.1.1"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Connection to APM Server   ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; URL to the APM Server
; Default value: http://localhost:8200
elastic_apm.server_url = "${APM_SERVER}"

; Secret token for the connection to APM Server
; https://www.elastic.co/guide/en/apm/server/current/secure-communication-agents.html#secret-token
; Default value: none
elastic_apm.secret_token =

;;;;;;;;;;;;;;;;;;;;;;;;;
; Supportability        ;
;;;;;;;;;;;;;;;;;;;;;;;;;

; Log level for syslog logging sink.
; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
; Default value: OFF
elastic_apm.log_level_syslog = DEBUG

; Log level for file logging sink.
; Also see log_file option.
; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
; Default value: INFO
elastic_apm.log_level_file = DEBUG

; Log level for standard error stream logging sink.
; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
; Default value: OFF
elastic_apm.log_level_stderr = DEBUG

; Log level used as the default when the more specific log_level_* option is not set.
;
; For example with the following configuration:
;
;                       elastic_apm.log_level_syslog = INFO
;                       elastic_apm.log_level_stderr =
;                       elastic_apm.log_level        = WARNING
;
; log levels are INFO for syslog and WARNING for stderr.
;
; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
; Default value: none
elastic_apm.log_level = DEBUG

elastic_apm.bootstrap_php_part_file=/var/www/html/vendor/elastic/apm-agent/src/bootstrap_php_part.php`

The data sent is the following:
`[Util] [util_for_PHP.c:222] [sendEventsToApmServer]     {"metadata":{"process":{"pid":280},"service":{"name":"application-name","agent":{"name":"php","version":"0.1-preview"},"language":{"name":"PHP","version":"7.3.21"},"runtime":{"name":"PHP","version":"7.3.21"}}}}`

When I use my extension, the following is the data being sent:
`[Util] [util_for_PHP.c:222] [sendEventsToApmServer]     {"metadata":{"process":{"pid":284},"service":{"name":"application-name","version":"1.1.1","environment":"production","agent":{"name":"php","version":"0.1-preview"},"language":{"name":"PHP","version":"7.3.21"},"runtime":{"name":"PHP","version":"7.3.21"}}}}`

**Comment by SergeyKleyman** [comment]
Yes, it seems you are right - `ini_get_all()` returns only registered ini options. I'll try to use something like `parse_ini_file(php_ini_loaded_file(), /* process_sections: */ false, INI_SCANNER_RAW)` instead. Additional advantage is PHP's automatic conversions (such converting string `off` into boolean `false`) won't be an issue as well.

**Comment by SergeyKleyman** [comment]
I pushed [the change](https://github.com/elastic/apm-agent-php/pull/144/commits/40c97dfdcf93572da9c3a8314111a6e2f0a1c544) to #144. Please let me know if solves the issue.

**Comment by miguelsimoes** [comment]
Still no luck (used your branch):
`[Util] [util_for_PHP.c:222] [sendEventsToApmServer]     {"metadata":{"process":{"pid":6381},"service":{"name":"Unnamed PHP service","agent":{"name":"php","version":"0.1-preview"},"language":{"name":"PHP","version":"7.3.21"},"runtime":{"name":"PHP","version":"7.3.21"}}}}`

Please note that even the service_name now is not applied.

**Comment by SergeyKleyman** [comment]
If you ran
```
php -r "var_dump(parse_ini_file(php_ini_loaded_file(), false, INI_SCANNER_RAW)['elastic_apm.service_name'])"\;
```
what do you get?

**Comment by miguelsimoes** [comment]
`2020-08-20 07:51:35.887791+00:00 [DEBUG]    [Configuration] [Parser.php:49] [parse] Input raw config snapshot doesn't have a value for the option - using default value {Option name: enabled, Option default value: true, namespace: Elastic\Apm\Impl\Config, class: Parser}
2020-08-20 07:51:35.889311+00:00 [DEBUG]    [Configuration] [Parser.php:49] [parse] Input raw config snapshot doesn't have a value for the option - using default value {Option name: environment, Option default value: <null>, namespace: Elastic\Apm\Impl\Config, class: Parser}
2020-08-20 07:51:35.890389+00:00 [DEBUG]    [Configuration] [Parser.php:49] [parse] Input raw config snapshot doesn't have a value for the option - using default value {Option name: service_name, Option default value: <null>, namespace: Elastic\Apm\Impl\Config, class: Parser}
2020-08-20 07:51:35.891652+00:00 [DEBUG]    [Configuration] [Parser.php:49] [parse] Input raw config snapshot doesn't have a value for the option - using default value {Option name: service_node_name, Option default value: <null>, namespace: Elastic\Apm\Impl\Config, class: Parser}
2020-08-20 07:51:35.893243+00:00 [DEBUG]    [Configuration] [Parser.php:49] [parse] Input raw config snapshot doesn't have a value for the option - using default value {Option name: service_version, Option default value: <null>, namespace: Elastic\Apm\Impl\Config, class: Parser}`

**Comment by SergeyKleyman** [comment]
And what did the command itself
```
php -r "var_dump(parse_ini_file(php_ini_loaded_file(), false, INI_SCANNER_RAW)['elastic_apm.service_name'])"\;
```
output?

Although the above example is not a good test since `elastic_apm.service_name` is registered by the extension.
I took the following part of php.ini file you pasted above:
```

[elastic_apm]

;
; Elastic PHP APM Agent
;
; See: https://github.com/elastic/apm-agent-php
;
extension = elastic_apm.so

; Boolean flag to enable/disable all of the agent's functionality.
; Possible values:
; false = Disabled
; true = Enabled
; Default value: true
elastic_apm.enabled = true

; Location of the
elastic_apm.log_file = "/var/log/directus/apm.log"

;;;;;;;;;;;;;;;;;;;;;;;;;
; Monitored service ;
;;;;;;;;;;;;;;;;;;;;;;;;;

elastic_apm.environment = "production"

; The required service's name to identify it later in the APM UI
; Please change to a to your use case appropiate name.
elastic_apm.service_name = "application-name"

; Set the service's version to compare historical private between deployments
; Default value: none
elastic_apm.service_version = "1.1.1"
```
I appended it to the end of php.ini in my environment and I tried the following commands:
```
php -r "var_dump(parse_ini_file(php_ini_loaded_file(), false, INI_SCANNER_RAW))"\; | grep -A 1 -i elastic
```
```
  string(14) "elastic_apm.so"
  ["elastic_apm.enabled"]=>
  string(4) "true"
  ["elastic_apm.log_file"]=>
  string(25) "/var/log/directus/apm.log"
  ["elastic_apm.environment"]=>
  string(10) "production"
  ["elastic_apm.service_name"]=>
  string(16) "application-name"
  ["elastic_apm.service_version"]=>
  string(5) "1.1.1"
```
```
php -r "var_dump(parse_ini_file(php_ini_loaded_file(), false, INI_SCANNER_RAW)['elastic_apm.environment'])"\;
```
```
string(10) "production"
```
```
php -r "var_dump(parse_ini_file(php_ini_loaded_file(), false, INI_SCANNER_RAW)['elastic_apm.service_version'])"\;
```
```
string(5) "1.1.1"
```


Could you please try them in your environment?

**Comment by miguelsimoes** [comment]
The PR can be closed as the implementation now in place works fine and as expected. Thank you for the fix.

**Pull request closed without merging**
