### PR TITLE
fix: add docker container id discovery for SystemData

### PR DESCRIPTION
**Pull request by zobo**

### CODE REVIEW

**Comment by SergeyKleyman** [comment]
@zobo Thank you very much for your contribution! Could you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by zobo** [comment]
Hum, did sign it, but CLA has not changed. Do I need to do anything else?

**Comment by zobo** [comment]
Will fix issues with tests.

**Comment by SergeyKleyman** [comment]
run elasticsearch-ci/docs

**Comment by SergeyKleyman** [comment]
@zobo It looks very good. I refactored MetadataDiscoverer::detectContainerId to make it testable and added unit test.
Please take a look at https://github.com/zobo/apm-agent-php/pull/1
BTW it's the first time I create "a PR for a PR" :) so please let me know if there is a better way to propose changes for a PR.

**Comment by zobo** [comment]
Fantastic. I did not initially focus so much on the tests side of the project, just plugged in the code I used in an old agent implementation I used. Now that I'm looking at it more closely I see it's really clean. Thanks for keeping the quality so high!

**Comment by zobo** [comment]
Eh, I choose merge instead of rebase by accident, hope that's ok.

**Comment by SergeyKleyman** [comment]
run elasticsearch-ci/docs

**Review by SergeyKleyman — APPROVED** [review]

**Comment by SergeyKleyman** [comment]
@zobo Do you have an example of `/proc/self/cgroup` and `/proc/self/mountinfo` content from AWS ECS container? I thought it might be nice to add that dataset to the unit test since the original issue (#823) was mentioning that particular use case (i.e., AWS ECS container).

BTW I missed [a bug in this PR](https://github.com/elastic/apm-agent-php/pull/966/files#diff-675acfaa32eb24af7b5c6f9501c96e38c79b2a80040cefcc3d1ca4f62e458d8bR133) in the review :( but we [fixed it](https://github.com/elastic/apm-agent-php/pull/975/commits/ab02f7573848322223222199bb490faa9d9a00d8#diff-675acfaa32eb24af7b5c6f9501c96e38c79b2a80040cefcc3d1ca4f62e458d8bR134) in PR #975 and it's already merged.

**Comment by zobo** [comment]
You are right, I just realized that too. I do not currently have any running beanstalks with containerized projects. I will ask around, but best if the OP provides some data.

**Pull request merged**
