### PR TITLE
Introduce server_ca_cert option

### LINKED ISSUE #430: Allow Custom CA Certificates
**Describe the bug**
Users who have custom certificate authorities in the chain are not able to use TLS validation, as there is no way to add more trusted CA certificates.

The Node agent has the option [serverCaCertFile](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#server-ca-cert-file), but the PHP agent does not have an equivalent option.

Disabling TLS verification is not an acceptable solution.

**To Reproduce**
1. Put the APM server behind a custom CA
2. Try to use the PHP Elastic APM Agent
3. Notice cert errors in the PHP logs
4. Try to find the option for custom CA certs
5. Fail to find such an option

**Expected behavior**
The agent should be usable with custom CAs in the chain without circumventing security.

### PR DESCRIPTION
**Pull request by wouterj**
Fixes #430

ElasticStack documentation recommends using a custom certificate authority for the stack.

At the moment of writing this PR, the PHP agent only allows disabling certificate verification. This is arguably not a great option, as it by-passes the security benefit of certificates. [Other APM agents](https://www.elastic.co/guide/en/apm/server/7.13/ssl-setup.html#ssl-server-authentication) have options to set the CA file that is used for communication with the APM server. This PR does the same for the PHP agent:

```
[elastic]
;...
elastic_apm.server_ca_cert: '/full/path/to/cacert.pem'
```

### CODE REVIEW

**Comment by SergeyKleyman** [comment]
Thank you very much for your contribution. It looks good. One possible (optional) improvement would be to add automated test(s) but I'm not sure what would be a way to implement it. Your suggestions are very welcome.

**Comment by wouterj** [comment]
To be honest, I've never written any C code before this PR, so I was already over the moon that I managed to create a working feature :)

I see this package does contain some functional tests in PHP to test the C extension: https://github.com/elastic/apm-agent-php/blob/master/tests/ElasticApmTests/ComponentTests/VerifyServerCertTest.php I guess what would be needed is somehow setup an APM server with a custom certificate authority and then test if we can correctly authenticate with that server?
Or do you want a more low-key unit test? (not sure if C unit tests are a thing)

**Comment by SergeyKleyman** [comment]
> Or do you want a more low-key unit test? (not sure if C unit tests are a thing)

For me personally it doesn't matter that much if the test is implemented in C or in PHP but I assume more people will find it easier to understand and maintain if it's implemented in PHP. But I would not focus at this level at this point. What I wanted to see is how this feature can be tested. I propose let's start simple - I think manual testing is enough at this point and we can create a follow up PR to add automated testing. The problem is that I am not familiar with this area (how to create a certificate based on CA, etc.). Would it be possible for you to provide steps you used to test this fix?

**Comment by wouterj** [comment]
Of course! (for reference, we're currently already using this patch on our machines)

The easiest is to use the certutil from elasticsearch:

1. Create a CA: `./bin/elasticsearch-certutil ca --pem` (+ unzip)
2. Create a certificate for the APM server: `./bin/elasticsearch-certutil cert --ca-cert <path-to-ca-crt>/ca.crt --ca-key <path-to-ca-key>/ca.key --pem --name localhost` (ca-certs from step 1)
3. Configure APM server with the `localhost.crt` and `localhost.key` generated in step 2
4. Configure the new `elastic_apm.server_ca_cert` agent setting in this PR to point to `<path-to-ca-crt>/ca.crt` from step 1

Now, the agent should be able to validate the certificates from the APM server.

**Pull request closed without merging**
