### PR TITLE
Create error event for PHP error only when in error_reporting()

### LINKED ISSUE #624: Allow users to control for which PHP errors agent creates APM error events
Follow up from [this comment](https://github.com/elastic/apm-agent-php/pull/619#issuecomment-1041392233)

It seems the most natural for the agent to abide by [`error_reporting()`](https://www.php.net/manual/en/function.error-reporting.php) and create error event only for PHP error types included in [`error_reporting()`](https://www.php.net/manual/en/function.error-reporting.php)

### PR DESCRIPTION
**Pull request by SergeyKleyman**
Closes #624

### CODE REVIEW

**Comment by GHostlyFOX** [comment]
Fine. And then because of the E_NOTICE flow, Alerts began to work according to the number of errors. The system considered them errors.

**Comment by GHostlyFOX** [comment]
If it would be possible to specify in the rules setup which events are considered errors. 
изображение

**Comment by SergeyKleyman** [comment]
> If it would be possible to specify in the rules setup which events are considered errors. изображение

@GHostlyFOX I'm not sure I understood 100% - could you clarify what you mean please? Is it something that doesn't work as expected?

**Comment by GHostlyFOX** [comment]
Here in APM it is possible to set up notifications if the number of errors suddenly starts to grow in a minute. But at the same time, it is impossible to specify which errors should be reacted to. Due to the fact that APM has now begun to register all E_NOTICE, it turned out that it began to grow, according to the system, the number of errors and the trigger fired. If it were possible to add filters to what type of errors to react to in the notification settings - for example, only to E_ERROR.

P.S. when will the error_reporting update be released?

**Comment by GHostlyFOX** [comment]
Thanks

**Comment by GHostlyFOX** [comment]
thank you

**Comment by SergeyKleyman** [comment]
@GHostlyFOX v1.4.2 was released. Please let me know if there are any issues.

**Comment by GHostlyFOX** [comment]
@SergeyKleyman Thank you. Installed the update, we'll see.

**Comment by GHostlyFOX** [comment]
I understand correctly that now if error_reporting(0) - APM will not write anything. And if error_reporting(E_ERROR) will it write to the log?

**Comment by kieranbrown** [comment]
@SergeyKleyman on the whole this is working great for us, got it installed on the majority of our production services, been waiting for this for a long time.

However, it's causing a segmentation fault on 1 of our services, resulting in a 502 bad gateway, this didn't occur <= v1.4.0. Going to do some more investigation and submit an issue once I've found the culprit.

`AH00052: child pid 32 exit signal Segmentation fault`

**Comment by SergeyKleyman** [comment]
@kieranbrown Could you please open a separate issue for us to investigate the crash? Thank you in advance. Also please provide  PHP agent's logs at `TRACE` level ([online documentation for the relevant configuration](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging))

**Comment by SergeyKleyman** [comment]
@GHostlyFOX 

> I understand correctly that now if error_reporting(0) - APM will not write anything.

I assume you refer to error APM events only (because `error_reporting()` doesn't have any effect on APM transactions and spans ). If `error_reporting()` doesn't include any PHP error types then PHP agent will not generate error events for any PHP errors but there are other circumstances when PHP agent generates error events which do not triggered by PHP errors. At the moment there is only one such use case: if HTTP response code is 5xx and there was an exception (even if the exception was caught) then PHP agent will generate error event based on that exception. Do you think you might need a way to enable/disable this aspect of PHP agent behavior?

> And if error_reporting(E_ERROR) will it write to the log?

I didn't test with `error_reporting(E_ERROR)` - [automated tests](https://github.com/elastic/apm-agent-php/blob/v1.4.2/tests/ElasticApmTests/ComponentTests/ErrorTest.php#L147) cover use cases including/excluding `E_NOTICE` or `E_WARNING`.

**Pull request merged**
