### PR TITLE
Small fixes to examples in docs

### PR DESCRIPTION
**Pull request by ArtemLavrentii**
While playing with examples I noticed that interface wasn't imported in it, but ElasticApm was.
There was also a missing commas in few places, I didn't check everything but did fix a few of them

### CODE REVIEW

**Comment by SergeyKleyman** [comment]
Hi @ArtemLavrentii,

Thank you very much for your contribution. It looks very good and I will gladly merge it but we need all the contributors to sign [Contributor License Agreement](https://www.elastic.co/contributor-agreement/) as it says in [CONTRIBUTING.md](https://github.com/elastic/apm-agent-php/blob/master/CONTRIBUTING.md#submitting-your-changes):
> Please make sure you have signed our [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). We are not asking you to assign copyright to us, but to give us the right to distribute your code without restriction. We ask this of all contributors in order to assure our users of the origin and continuing existence of the code. You only need to sign the CLA once.

**Comment by ArtemLavrentii** [comment]
@SergeyKleyman I did that after I have opened this PR. Is there anything else that I need to do ? Do I need to re-open the PR ?

**Comment by SergeyKleyman** [comment]
I guess it took some time to take effect - it's all good now. I'll merge your PR. Thank you again for your contribution.

**Review by SergeyKleyman — COMMENTED** [review]
LGTM

**Pull request merged**
