### PR TITLE
Implemented auto-instrumentation for PHP (user-land) code

### LINKED ISSUE #60: Add support for PHP user-land code auto-instrumentation
For example to support auto-instrumenting [Guzzle HTTP client](http://docs.guzzlephp.org/) although particularly for Guzzle we might be okay without instrumenting PHP user-land code because IIUC Guzzle uses curl behind the scenes and curl is an extension and the  agent already supports instrumenting methods/functions provided by PHP extensions.

### LINKED ISSUE #205: Add support for Laravel framework
#258 is a prerequisite

Mentioned at https://discuss.elastic.co/t/have-any-roadmap-for-supporting-php-frameworks/253892

### PR DESCRIPTION
**Pull request by SergeyKleyman**
Closes #60.
Closes #205.

### CODE REVIEW

**Comment by devfrey** [comment]
Apologies if this is a stupid question, but how does this enable or facilitate auto instrumentation for frameworks? Could you maybe provide an example?

By the way, the related issue for Laravel auto instrumentation was closed. Was this intentional?

**Comment by SergeyKleyman** [comment]
@devfrey You are right - I submitted a partial PR by mistake to resolve another issue. I'll reopen #60 and #205 and I'll submit related changes to those issues in the next few days.

**Comment by devfrey** [comment]
@SergeyKleyman Thank you for your work. Really looking forward to getting started with the official PHP agent for Elastic APM!

**Comment by jpcercal** [comment]
@SergeyKleyman thank you very much for making it possible. I'm looking forward to having the next release available. Any thoughts on when will a release be available other than in a beta stage?

**Comment by alex-fedotyev** [comment]
> @SergeyKleyman thank you very much for making it possible. I'm looking forward to having the next release available. Any thoughts on when will a release be available other than in a beta stage?

Hi @jpcercal !
We are working towards a GA version of the agent in one of the upcoming 7.x releases and making great progress!
Unfortunately I can't share more details on the dates yet.

**Comment by zorino** [comment]
Hi @alex-fedotyev,

Is there any update on this issue ? I am using the agent with the laravel framework pour there's no function call trace reported to the APM server.

Thank you.

**Pull request merged**
