### PR TITLE
[Closes #582] Support php 8.1.0

### LINKED ISSUE #582: Support PHP 8.1
I'm trying to install the agent on PHP 8.1, and apm agent doesn't support this PHP version

Error when compiling:

```
/apm-agent-php/src/ext/util_for_PHP.c: In function 'loadPhpFile':
/apm-agent-php/src/ext/util_for_PHP.c:48:5: warning: passing argument 1 of 'php_stream_open_for_zend_ex' from incompatible pointer type [enabled by default]
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: expected 'struct zend_file_handle *' but argument is of type 'const char *'
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:48:5: warning: passing argument 2 of 'php_stream_open_for_zend_ex' makes integer from pointer without a cast [enabled by default]
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: expected 'int' but argument is of type 'struct zend_file_handle *'
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:48:5: error: too many arguments to function 'php_stream_open_for_zend_ex'
     ret = php_stream_open_for_zend_ex( filename, &file_handle, USE_PATH | STREAM_OPEN_FOR_INCLUDE );
     ^
In file included from /apm-agent-php/src/ext/util_for_PHP.c:21:0:
/usr/include/php/main/php_main.h:43:12: note: declared here
 PHPAPI int php_stream_open_for_zend_ex(zend_file_handle *handle, int mode);
            ^
/apm-agent-php/src/ext/util_for_PHP.c:65:9: warning: implicit declaration of function 'zend_file_handle_dtor' [-Wimplicit-function-declaration]
         zend_file_handle_dtor( &file_handle );
         ^
make: *** [util_for_PHP.lo] Error 1
```

### PR DESCRIPTION
**Pull request by Sharoff45**
Issue: https://github.com/elastic/apm-agent-php/issues/582

### CODE REVIEW

**Comment by Sharoff45** [comment]
run elasticsearch-ci/docs

**Comment by Sharoff45** [comment]
it would be great to add a build under 8.1 to CI

**Comment by Sharoff45** [comment]
@SergeyKleyman , what needs to be done to merge the request?

**Comment by SergeyKleyman** [comment]
@Sharoff45 Thank you for contributing. I will add instructions for our CI to actually start testing on PHP 8.1 and I will review your changes ASAP.

**Comment by antoniovj1** [comment]
Hey! If you need some help to test this PR, let me know :+1:

**Comment by lku** [comment]
I would kindly suggest the move forward with the supported PHP versions. PHP 8.0 is EOL this year https://www.php.net/supported-versions.php, 7.2 is history.

If I am not mistaken, the old releases stay there. If someone needs to use PHP 7.2, he can.

On the other hand, if PHP 8.1 is not supported when PHP 8.0 is EOL, I think some organizations will move to other solutions.

**Comment by antoniovj1** [comment]
In addition to @lku response I'll add the PHP will be mandatory for updating Symfony in the near future an also I think enums are an important PHP feature.

https://symfony.com/blog/symfony-6-1-will-require-php-8-1

**Comment by SergeyKleyman** [comment]
Implemented in #604.
Thank you @Sharoff45 for initiating the process :)

**Comment by lku** [comment]
Thank you, @SergeyKleyman . Do you know how long it takes to create distro packages on the release page? I can test it on quite a few projects/environments, or should I build from the source atm?

**Comment by SergeyKleyman** [comment]
@lku Unfortunately we are dealing with some issues in our CI that builds the binaries and publishes them to Github. We are actively working on fixing the issues but I don't the ETA. You can either build from source or you can try [binaries saved by PR CI](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-php%2Fapm-agent-php-mbp%2FPR-652/detail/PR-652/1/artifacts/). Please note that unlike the binaries that are published on Github binaries saved by PR CI are not signed.

**Pull request closed without merging**
