### PR TITLE
.ci: remove Integration Tests stage

### PR DESCRIPTION
**Pull request by axw**
See https://github.com/elastic/apm-integration-testing/issues/1523

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@axw Did you mean to assign the @elastic/apm-agent-ruby to review this? Perhaps @elastic/apm-agent-php ?

**Comment by axw** [comment]
Thanks @cachedout :)

**Review by SergeyKleyman — APPROVED** [review]

**Comment by axw** [comment]
@SergeyKleyman are those `lifecycle-*` failures unrelated? Is this safe to merge?

**Comment by SergeyKleyman** [comment]
> @SergeyKleyman are those `lifecycle-*` failures unrelated? Is this safe to merge?

@axw Yes, those failures are unrelated - it's CI infrastructure issue (it fails to clean up workspace on Jenkins workers at the very start). I think it's safe to merge.

**Comment by cachedout** [comment]
@SergeyKleyman Is this workspace cleanup issue something that happens often? Let us know if this is something we should be investigating. Thanks.

**Comment by SergeyKleyman** [comment]
> @SergeyKleyman Is this workspace cleanup issue something that happens often? Let us know if this is something we should be investigating. Thanks.

@cachedout It started a couple of days ago and now it happens every other PR. We have a Slack thread with @v1v on this issue.

**Pull request merged**
