### PR TITLE
Fixed error events for PHP errors

### LINKED ISSUE #300: PHP errors are not reported as APM error events
**Describe the bug**

Is error reporting working for the PHP Agent Beta?  

I ask because I was able to install the agent and get transactions reporting into an Elastic Cloud instance (yay).  However, errors were _not_ being reported in.

**To Reproduce**

1. Create a same program on your PHP Enabled webserer, as defined below
1. Confirm the fatal and notice level errors
2. Install the Elastic Agent via the .deb file and configure credentials via an `ini` file
3. Restart your web server/php-process to enable the agent
4. Reload the page and reproduce the errors
5. Change the call to the `add` function to `add(2,2)` to remove the fatal error
6. Reload the page and confirm the notice level error remains

**Expected behavior**
Errors are available in your elastic/kibana instance

**Actual behavior**
No errors appears in your elastic/kibana instance

Here's the program mentioned above

```
<?php
ini_set('display_errors','1');
function add($one, $two) {
    return $one + $two;
}

function main($argv) {
    echo add(2);
}
main($notDefined);
```

and a screencap of the errors

Screen Shot 2020-11-19 at 10 34 50 AM

Also, attaching a `phpinfo()` page from the server.  [info.zip](https://github.com/elastic/apm-agent-php/files/5568944/info.zip)

### LINKED ISSUE #409: Sending error results to Elastic APM
For error transactions like 500/404, currently not able to record into error tab(See attachment). Also Can we have the details of error transaction.
image

### LINKED ISSUE #585: Include call stack trace in error events
APM Server intake API allows stack trace in error events under [`exception` sub-object](https://github.com/elastic/apm-server/blob/v7.0.0/docs/spec/errors/error.json#L73).

### PR DESCRIPTION
**Pull request by SergeyKleyman**
Closes #300
Closes #409
Closes #585

### CODE REVIEW

**Comment by GHostlyFOX** [comment]
When will yum repository update?

**Comment by SergeyKleyman** [comment]
It's already in main branch and we plan to release it as v1.4.1 today.

**Comment by GHostlyFOX** [comment]
Rebuilt from source.
The error list is still empty.

**Comment by apit** [comment]
using v1.4.1.deb. still empty. php-fpm 7.4.27, elastic 7.17.0

**Comment by SergeyKleyman** [comment]
Thank you for reporting it. Could you please provide the following information to help us investigate these issues:

- [ ] PHP agent logs at `TRACE` level ([online documentation for the relevant configuration](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging)) covering the execution of the  use case when APM error event should have been created but it wasn't
- [ ] Does your application use a web framework (such as Laravel) and if so which one?
- [ ] What does your application do that should cause APM agent to create an error event?
    - [ ] Does the application trigger PHP error (i.e., old legacy pre-exception mechanism, for example by referencing undefined variable)?
    - [ ] Does the application throw an exception?
        - [ ] Is the exception caught? If so is it caught by the application's code or the web framework?
    - [ ] Does the application trigger error using some mechanism specific to the web framework? If so how exactly does the application trigger the error?
- [ ] What is the response's HTTP status code?

**Comment by GHostlyFOX** [comment]
1. Trace - turned on. Where can I see his results?

2. Used. Laravel on one server, Bitrix on another

3. The code costs a lot Exception, and I just tried to specifically make a mistake in the code by disabling all logging interceptors.

4. Error response code - 500 

изображение

**Comment by GHostlyFOX** [comment]
изображение

**Comment by GHostlyFOX** [comment]
I see that the page was completed with an error, but what error is not written anywhere. 

изображение

**Comment by SergeyKleyman** [comment]
@GHostlyFOX - thank you for this info - could you please provide PHP agent logs at `TRACE` level ([online documentation for the relevant configuration](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging)) covering the execution of the  use case when APM error event should have been created but it wasn't?

**Comment by GHostlyFOX** [comment]
What EMail should the file be sent to?

**Comment by apit** [comment]
1. `elastic_apm.log_level_syslog=TRACE`
2. Laravel 5.7
3. i tried scenarios:
    - throw exception, handled by laravel exception handler
    - syntax error in controller, handled by laravel exception handler
    - syntax error in public/index.php -> php exception handler
4. status code for all above are 500

**Comment by GHostlyFOX** [comment]
My  [unit.log](https://github.com/elastic/apm-agent-php/files/8079051/unit.log)

**Comment by GHostlyFOX** [comment]
Sorry. I found my mistake when Trace himself looked. Everything is working.

**Comment by SergeyKleyman** [comment]
@GHostlyFOX 

> Sorry. I found my mistake when Trace himself looked. Everything is working.

No problem. I would like to make sure I understood you correctly - do you mean that you do get APM error events with agent?1.4.1?

**Comment by SergeyKleyman** [comment]
@apit Thank you for the provided information. It seems the log is only from web service daemon (is it a Docker container since PID:1?) (). HTTP requests are actually handled by the spawned child worker processes and we need agent's logs from those processes. You need to make sure that PHP agent in context of those processes also logs at level `TRACE`. I see that you set log level via `.ini` file. Instead you can set `ELASTIC_APM_LOG_LEVEL` environment variable to `TRACE`. If you set environment variable for the whole Docker container (assuming that it's a Docker container) then all the processes inside the container will automatically inherit it.

**Comment by GHostlyFOX** [comment]
And how to regulate the level of logging?
I am now logging and E_NOTICE although I specified in the settings - ERROR 

elastic_apm.environment = "production"
elastic_apm.log_level = "ERROR"
elastic_apm.log_level_stderr = "ERROR"
elastic_apm.log_level_syslog = "ERROR"

**Comment by SergeyKleyman** [comment]
@GHostlyFOX You are right - currently there's no way to control for which PHP error the agent creates APM error events. I've created a new issue (Allow users to control for which PHP errors agent creates APM error events #624) to fix that.

**Comment by SergeyKleyman** [comment]
I think

**Comment by apit** [comment]
yes, it is a container. sorry, i also looked for the wrong service in Kibana; for 1.4.1 i overlooked that i changed the name in .ini. it's working :+1: 

btw, setting env still produce same log, stopping at `Exiting...`.

**Comment by SergeyKleyman** [comment]
@apit I'm glad to hear that the fix works for you.
Regarding the logs could you please upload the log generated when setting log level by environment variable?

**Comment by GHostlyFOX** [comment]
@SergeyKleyman yes, error_reporting() would be enough to control the level. I just tried to set them up but it didn't work.

**Pull request merged**
