### PR TITLE
[packaging] Support default template

### PR DESCRIPTION
**Pull request by v1v**
### What

Enable template configuration.

### Issues

Caused by https://github.com/elastic/apm-agent-php/issues/302

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Review by SergeyKleyman — APPROVED** [review]
It looks very good.

**Review by SergeyKleyman — COMMENTED** [review]
Maybe `elastic-apm-custom-template.ini` instead of `elastic-apm-template.ini` will make it clear what is the template for. WDYT?

**Comment by v1v** [comment]
> Maybe elastic-apm-custom-template.ini instead of elastic-apm-template.ini will make it clear what is the template for. WDYT?

Should the enabled property be set true?

**Comment by SergeyKleyman** [comment]
> Should the enabled property be set true?

Yes `enabled` is true by default. I now see why you have asked - there's an error in [the online docs for `enabled`](https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-enabled) which says that the default is `false`. I'll fix it ASAP.

**Comment by v1v** [comment]
### Tests

```bash
wget "https://apm-ci.elastic.co/job/apm-agent-php/job/apm-agent-php-mbp/job/PR-317/3/artifact/build/packages/*zip*/packages.zip" -O packages.zip
unzip packages.zip
mkdir -p build
mv packages build/packages
make -C packaging prepare-deb deb-install
### while it's running then
docker ps
docker exec -ti infallible_franklin cat /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini
; This file contains the various settings for the Elastic APM PHP agent. For
; further details refers to the following URL:
; https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html
;

[elastic]
;elastic_apm.enabled = true
;elastic_apm.api_key = "REPLACE_WITH_API_KEY"
;elastic_apm.environment = "production"

```

**Pull request merged**
