### PR TITLE
Bump maximum supported PHP version

### PR DESCRIPTION
**Pull request by onlineth**
PHP 8.0 supported since v1.1

### CODE REVIEW

**Comment by onlineth** [comment]
The Contributor Agreement has been signed.

**Comment by SergeyKleyman** [comment]
Thank you for the contribution but it's already updated as you can see at https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html
It was fixed in https://github.com/elastic/apm-agent-php/pull/421 but it became visible at elastic.co only yesterday when I merged 
the fix to 1.x branch (the documentation is built from 1.x branch). I should have done it right after merging https://github.com/elastic/apm-agent-php/pull/421 - something to remember for the next documentation change :)

**Comment by SergeyKleyman** [comment]
Actually you are correct - this part of the documentation is not fixed yet. Could you [sign the Contributor License Agreement](https://github.com/elastic/apm-agent-php/blob/master/CONTRIBUTING.md#submitting-your-changes),  please?

**Comment by onlineth** [comment]
For sure, I signed it about half an hour ago and I think that caused the cla-checker-service bot to update its comment.

**Pull request merged**
